### ISSUE TITLE
message after the optin is static

### ISSUE THREAD

**Issue by tttp** [WeMoveEU/bsd_api#19]
so after the confirm url, we redirect to a "thank you" page.

We need to be able to customize that thank you page. Two options:
1) we add a new custom field "redirect_url" on each campaign
2) we add a "thank you" custom field in each campaign and we display it instead of doing a redirect

My preference is for 2 right now, but not strong preference if you have a better idea.

Can you ping me before pushing on prod? we are going to have a campaign running

**Comment by scardinius** [comment]
Hi @tttp. What do you think about such solution?

* new page on url civicrm/speakout/thankyou based on class CRM_Bsd_Page_ThankYou extends CRM_Core_Page {}
* campaign_id will be added earlier here: https://github.com/WeMoveEU/bsd_api/blob/master/CRM/Bsd/Page/BSD.php#L97
* this line will be changed to new url with parameter campaing_id
https://github.com/WeMoveEU/bsd_api/blob/master/CRM/Bsd/Page/Confirm.php#L58
* I will retrieve custom values such as language (in order to set up title of page) and thank_you text from civicrm_campaign.id value 
* In addition this solution could be extended to sharing actions like facebook and twitter

**Comment by tttp** [comment]
Hi,

so yes to get the language back up to the thank you page, but instead of managing the display yourself, just redirect to the post confirm page, but add the language code, eg:

https://www.wemove.eu/en/post_confirm
https://www.wemove.eu/fr/post_confirm

drupal will take care of dealing with the translations

**Comment by scardinius** [comment]
ok, but As I understand your proposal is customizing only by language. That's enough? 
So in this case it's not necessary to create new custom field thank_you.

**Comment by tttp** [comment]
right, right now per language only. Could you add a ?campaign=id to the post_confirm so we could customise the thank you message if needed?

**Comment by scardinius** [comment]
yes, of course.

**Comment by scardinius** [comment]
`The requested page "/es/post_confirm" could not be found.`
I think the page post_confirm is not prepared for such urls. There is a spanish version but it works on different url: https://www.wemove.eu/es/tu-acci%C3%B3n-ha-sido-confirmada

How can I improve this?

**Comment by scardinius** [comment]
Urls like a `/es/post_confirm` work now, great :)
